Add README file for developers
TNO-Tulipa/TulipaBulb.jl pull request #5
Opened 2023-08-10 08:18 UTC by datejada

# Pull request details

## Describe the changes made in this pull request

This file has the developers' guide for contributions to this repository.

## List of related issues or pull requests

Closes #1 

## Collaboration confirmation

As a contributor I confirm

- [x] I read and followed the instructions in README.dev.md
- [NA] The documentation is up to date with the changes introduced in this Pull Request (or NA)
- [x] Tests are passing
- [x] Lint is passing

2023-08-10 12:42 UTC, abelsiqueira commented
I think it would be better to add a lint workflow (#8) before this so we can check that it has the right format.

2023-08-10 15:38 UTC, datejada commented
The pull request (#20) solves the issue (#8) of adding a lint workflow to the repository

2023-08-16 12:42 UTC, nope82 requested changes
Hi Diego, I left just a very small comments to the great work you already did. I believe that

2023-08-16 12:42 UTC, nope82 commented on README.dev.md
> +- Add this repo as upstream with
```suggestion
1. Fork this repository.
2. Clone your fork.
3. Add this repo as upstream with the following command:
```

2023-08-16 12:42 UTC, nope82 commented on README.dev.md
> +- Add this repo as upstream with
I would put is as an enumeration list to give it more of a workflow feeling, what do you think?

2023-08-16 12:42 UTC, nope82 commented on README.dev.md
> +- Run the tests to make sure that everything is working as expected.
```suggestion
5. Open this project in your editor. 
6. On Julia, activate and instantiate the project under the package mode.
7. Run the tests to make sure that everything is working as expected.
```

2023-08-16 12:42 UTC, nope82 commented on README.dev.md
> +**Note:** on subsequent occassions when you need to run pre-commit in a new shell, you will need to activate the Python virtual environment.
```suggestion
**Note:** on subsequent occassions when you need to run pre-commit in a new shell, you will need to activate the Python virtual environment. If so, do the following:
```

2023-08-16 12:42 UTC, nope82 commented on README.dev.md
> +- Commit message
```suggestion

- Commit message
```

2023-08-16 12:42 UTC, nope82 commented on README.dev.md
> +- Try to create "atomic git commits" (recommended reading: [The Utopic Git History](https://blog.esciencecenter.nl/the-utopic-git-history-d44b81c09593))
```suggestion

- Try to create "atomic git commits" (recommended reading: [The Utopic Git History](https://blog.esciencecenter.nl/the-utopic-git-history-d44b81c09593))
```

2023-08-16 14:01 UTC, merged